// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk27Pcndn1II5_H_uFou4dirgjSOiQ-ns',
    appId: '1:1033834360605:web:f9670c4a4a70325372fbf4',
    messagingSenderId: '1033834360605',
    projectId: 'daan-i',
    authDomain: 'daan-i.firebaseapp.com',
    storageBucket: 'daan-i.appspot.com',
    measurementId: 'G-PQZVQKQSZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9iuyW6khJ-houQAkNB4-CDe9ik6Zdwdg',
    appId: '1:1033834360605:android:268aa1c96f307df372fbf4',
    messagingSenderId: '1033834360605',
    projectId: 'daan-i',
    storageBucket: 'daan-i.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLG54opAGTeo0OCm4HTE3LSSs9p6n3FTU',
    appId: '1:1033834360605:ios:f8f3627d7153625e72fbf4',
    messagingSenderId: '1033834360605',
    projectId: 'daan-i',
    storageBucket: 'daan-i.appspot.com',
    iosBundleId: 'com.example.daanIApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLG54opAGTeo0OCm4HTE3LSSs9p6n3FTU',
    appId: '1:1033834360605:ios:62c21aaf81cd3f3b72fbf4',
    messagingSenderId: '1033834360605',
    projectId: 'daan-i',
    storageBucket: 'daan-i.appspot.com',
    iosBundleId: 'com.example.daanIApp.RunnerTests',
  );
}
